import os
import sys
import uuid
import time
import argparse
from pathlib import Path

# Add backend/ folder to path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.config import settings
from app.core.database import SessionLocal, engine, Base
from app.services.knowledge_base_helper import get_knowledge_base_context, enhance_prompt_with_context
from app.services.pravah_adapter import pravah_adapter
from app.services.prana_replay_orchestrator import prana_replay_orchestrator
from app.core.context import set_trace_id

# Optional ML import check
try:
    from app.services.sovereign_lm_core import generate as sovereign_generate, is_model_loaded
    ML_SUPPORTED = True
except ImportError:
    ML_SUPPORTED = False

async def run_pilot(query: str, board: str, medium: str, class_std: int, run_id: str):
    # Ensure DB tables exist
    Base.metadata.create_all(bind=engine)
    
    # 1. Establish session trace ID
    trace_id = f"yotta-pilot-{uuid.uuid4().hex[:12]}"
    set_trace_id(trace_id)
    
    print("=" * 60)
    print(f" YOTTA SHAKTISTUDIO SOVEREIGN PILOT RUNNER")
    print(f" Query      : '{query}'")
    print(f" Trace ID   : {trace_id}")
    print(f" Run ID     : {run_id}")
    print(f" Syllabus   : Board={board.upper()}, Medium={medium.lower()}, Class={class_std}")
    print("=" * 60)
    
    # 2. Telemetry: Emit user interaction request
    pravah_adapter.emit_signal(
        event_type="user_action",
        action="chat_request",
        payload={
            "conversation_id": trace_id,
            "use_rag": True,
            "message": query,
            "board": board,
            "medium": medium,
            "class_std": class_std,
            "run_id": run_id
        }
    )
    
    # 3. Curriculum Retrieval (RAG)
    print("\n[Step 1/4] Querying Vector Store (Curriculum Retrieval)...")
    filter_metadata = {
        "board": board.upper(),
        "medium": medium.lower(),
        "class_std": class_std
    }
    
    kb_result = get_knowledge_base_context(
        query=query,
        top_k=3,
        filter_metadata=filter_metadata,
        use_knowledge_base=True
    )
    
    context = kb_result.get("context", "")
    print(f"  [OK] Retrieved context length: {len(context)} characters")
    if context:
        print(f"  [OK] Retrieval Source: {kb_result['results'][0]['metadata'].get('source', 'Unknown')}")
    else:
        print("  [WARN] No curriculum chunks found in vector database. Fallback to base knowledge.")
        
    # 4. Grounded Prompt Assembly
    base_system_message = "You are Gurukul, an AI coding tutor and educational guide."
    system_prompt = enhance_prompt_with_context(
        base_prompt=base_system_message,
        query=query,
        context=context,
        include_context_instruction=True
    )
    
    # 5. Local Sovereign LLM Core Inference
    print("\n[Step 2/4] Executing Grounded Inference (Sovereign LLM Core)...")
    replayed_response = None
    model_source = "Local Llama 3.2 3B (Peft/LoRA)"
    
    if ML_SUPPORTED and is_model_loaded():
        try:
            replayed_response = await sovereign_generate(
                prompt=query,
                system_prompt=system_prompt,
                max_tokens=256,
                temperature=0.0 # Deterministic!
            )
        except Exception as e:
            print(f"  [WARN] Sovereign LM execution error: {e}")
            
    if not replayed_response:
        # Fallback to local deterministic generator (or Groq if key is present)
        try:
            if settings.GROQ_API_KEY and not settings.GROQ_API_KEY.startswith("your_"):
                from groq import Groq
                client = Groq(api_key=settings.GROQ_API_KEY)
                completion = client.chat.completions.create(
                    model="llama-3.3-70b-versatile",
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": query}
                    ],
                    temperature=0.0,
                    max_tokens=256
                )
                replayed_response = completion.choices[0].message.content
                model_source = "Groq Llama 3.3 70B (Remote Fallback)"
        except Exception:
            pass
            
    if not replayed_response:
        raise RuntimeError("Production inference failed: No response generated by local sovereign LLM or remote fallback API (mocks disabled).")
        
    print(f"  [OK] Generated response from: {model_source}")
    print(f"  [OK] Response Preview: {replayed_response[:120]}...")
    
    # 6. Telemetry: Emit completion event
    import hashlib
    output_hash_val = hashlib.sha256(replayed_response.encode('utf-8')).hexdigest()
    replay_verification_val = hashlib.sha256(f"{replayed_response}:{run_id}".encode('utf-8')).hexdigest()
    retrieved_doc_ids = [res.get('metadata', {}).get('id', 'Unknown') for res in kb_result.get('results', [])] if kb_result.get('results') else []

    pravah_adapter.emit_signal(
        event_type="user_action",
        action="chat_response_generated",
        status="success",
        payload={
            "conversation_id": trace_id,
            "response": replayed_response,
            "run_id": run_id,
            "prompt": query,
            "retrieval_context": context,
            "retrieved_document_ids": retrieved_doc_ids,
            "model_identifier": model_source,
            "model_version": "1.0.0",
            "inference_configuration": {"temperature": 0.0, "max_tokens": 256},
            "output_hash": output_hash_val,
            "replay_verification": replay_verification_val
        }
    )
    print("  [OK] Telemetry signals emitted to Pravah and ingested to local database.")
    
    # 7. Replay Reconstruction & Verification
    print("\n[Step 3/4] Replaying & Verifying Reconstructed Student Journey...")
    # Sleep briefly to ensure database write is completed
    time.sleep(0.5)
    
    with SessionLocal() as db:
        replay_result = prana_replay_orchestrator.orchestrate_replay(
            db,
            run_id=run_id
        )
        
    # Find matching validation entries
    system_result = replay_result.get("system_results", {}).get("gurukul", {})
    educational_journeys = system_result.get("normalized_output", {}).get("educational_journeys", {})
    journey = educational_journeys.get(trace_id, {})
    
    print(f"  [OK] Replay Status: {replay_result['replay_status']}")
    if journey:
        print(f"  [OK] BLEU Similarity Score : {journey.get('bleu_score', 0.0)}")
        print(f"  [OK] ROUGE Similarity Score: {journey.get('rouge_score', 0.0)}")
        print(f"  [OK] Journey Match Status  : {journey.get('match_status')}")
    else:
        print("  [WARN] Journey not found in replay output. Check DB logs.")
        
    # 8. Print Proof Output Summary
    print("\n" + "=" * 60)
    print(" [Step 4/4] SOVEREIGN RUNTIME INFERENCE PROOF SUMMARY")
    print("=" * 60)
    print(f" Original Question  : {query}")
    print(f" Model Source Used  : {model_source}")
    print(f" Replayed Response  : {replayed_response}")
    print(f" Trace ID           : {trace_id}")
    print(f" Validation Outcome : {replay_result['replay_status']}")
    print("=" * 60 + "\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Gurukul Yotta ShaktiStudio Sovereign Pilot")
    parser.add_argument("--query", type=str, default="What is photosynthesis?", help="Student query to evaluate")
    parser.add_argument("--board", type=str, default="NCERT", help="Active educational board standard")
    parser.add_argument("--medium", type=str, default="en", help="Educational medium (e.g. en, hi)")
    parser.add_argument("--class-std", type=int, default=10, help="Educational class level")
    parser.add_argument("--run-id", type=str, default="yotta-sprint-validation-run", help="Unique run identifier for replay tracking")
    
    args = parser.parse_args()
    
    import asyncio
    asyncio.run(run_pilot(
        query=args.query,
        board=args.board,
        medium=args.medium,
        class_std=args.class_std,
        run_id=args.run_id
    ))
