import http from 'k6/http';
import { check, sleep } from 'k6';

/**
 * TRACE CONTINUITY TEST
 * Objective: Prove that a single Trace ID can be propagated across microservices.
 */

const BASE_URL = __ENV.BASE_URL || 'http://127.0.0.1'; // Backend Ingress
const TTS_URL = __ENV.TTS_URL || 'http://localhost:8007';   // TTS Service Ingress

export const options = {
  vus: 1,
  iterations: 1, // Single run for clear log matching
};

export default function () {
  // --- STEP 1: Call Backend ---
  console.log("Step 1: Calling Backend Chat...");

  const token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImV4cCI6MTc3OTI3OTM0MCwiaWF0IjoxNzc4Njc0NTQwLCJqdGkiOiJhMzJmNTJkNy1lYTVkLTQ2MjItYmZhMi1lODY0ZWYyZTk0MDYiLCJzZXNzaW9uX2lkIjoiYTMyZjUyZDctZWE1ZC00NjIyLWJmYTItZTg2NGVmMmU5NDA2In0.9INhsIpcgbSSxM8Q7Pc8FDhdedDRZ-OnL_9vh-xoqlo';
  let chatRes = http.post(`${BASE_URL}/api/v1/chat`, JSON.stringify({
    "message": "Hii",
    "conversation_id": "abc12",
    "provider": "auto",
    "use_rag": true
  }), {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ' + token,
    }
  });

  // Extract the Trace ID generated by the Backend
  let traceId = chatRes.headers['X-Trace-Id'];

  if (!traceId) {
    console.error("FAILED: Backend did not return X-Trace-Id header!");
    return;
  }

  console.log(`[BACKEND] Status: ${chatRes.status} | Trace ID Received: ${traceId}`);

  // --- STEP 2: Propagate to TTS Service ---
  console.log(`Step 2: Propagating Trace ID [${traceId}] to TTS Service...`);

  let ttsRes = http.post(`${TTS_URL}/api/generate`, {
    text: 'Validating distributed trace propagation'
  }, {
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'X-Trace-ID': traceId // <--- MANUALLY PASSING THE ID TO PROVE CONTINUITY
    }
  });

  // Extract the Trace ID returned by TTS
  let ttsTraceId = ttsRes.headers['X-Trace-Id'];

  console.log(`[TTS] Status: ${ttsRes.status} | Trace ID Received: ${ttsTraceId}`);

  // --- STEP 3: Final Verification ---
  check(ttsRes, {
    'Trace ID is preserved': (r) => r.headers['X-Trace-Id'] === traceId,
  });

  if (traceId === ttsTraceId) {
    console.log("------------------------------------------------------------");
    console.log("SUCCESS: Trace ID remained identical across both services!");
    console.log(`FINAL PROOF ID: ${traceId}`);
    console.log("------------------------------------------------------------");
  } else {
    console.log("FAILED: Trace ID changed between services.");
  }
}
