import { createContext, useContext, useEffect, useRef } from 'react';
import { useAuth } from './AuthContext';
import { getPacketBuilder, resetPacketBuilder } from '../utils/prana_packet_builder';
import { getCurrentContext } from '../utils/contextManager';
import API_BASE_URL from '../config';

const PranaContext = createContext();

// Context provider that supplies user context to PRANA and initializes it on login
export const PranaProvider = ({ children }) => {
  const { user, loading } = useAuth();
  const packetBuilderRef = useRef(null);
  const pranaInitializedRef = useRef(false);

  // Initialize PRANA when user logs in
  useEffect(() => {
    // Wait for PRANA to be available (loaded from gurukul_prana.js)
    if (typeof window === 'undefined' || !window.PRANA) {
      return;
    }

    // Only initialize if user is logged in and PRANA hasn't been initialized yet
    if (user && !loading && !pranaInitializedRef.current) {
      try {
        const currentCtx = getCurrentContext();
        
        // Initialize PRANA with user context
        const pranaInstance = window.PRANA.init({
          system_type: 'gurukul',
          role: 'student',
          user_id: user.id || null,
          session_id: currentCtx.session_id || null,
          lesson_id: currentCtx.lesson_id || null,
          // Gurukul backend uses /api/v1 prefix
          bucket_endpoint: `${API_BASE_URL}/api/v1/bucket/prana/ingest`,
        });
        
        packetBuilderRef.current = pranaInstance?.packetBuilder || getPacketBuilder();
        pranaInitializedRef.current = true;
        console.log('[PRANA] Initialized after user login');
      } catch (e) {
        console.error('[PRANA] Failed to initialize:', e);
      }
    }
    
    // Stop PRANA when user logs out
    if (!user && !loading && pranaInitializedRef.current) {
      resetPacketBuilder();
      pranaInitializedRef.current = false;
      packetBuilderRef.current = null;
      console.log('[PRANA] Stopped after user logout');
    }
  }, [user, loading]);

  // Provide context to PRANA packet builder
  const getContext = () => {
    // Use context manager to get current context (this will auto-generate session_id if missing)
    const currentCtx = getCurrentContext();
    
    if (!user || loading) {
      return {
        user_id: null,
        session_id: currentCtx.session_id || null,
        lesson_id: currentCtx.lesson_id || null
      };
    }

    return {
      user_id: user.id || currentCtx.user_id || null,
      session_id: currentCtx.session_id || null, // Already generated by getCurrentContext()
      lesson_id: currentCtx.lesson_id || null
    };
  };

  // Register context provider with packet builder when available
  useEffect(() => {
    const builder = packetBuilderRef.current || getPacketBuilder();
    if (builder && typeof builder.registerContextProvider === 'function') {
      builder.registerContextProvider({ getContext });
      console.log('[PRANA] Connected to AuthContext');
    }
  }, [user, loading]);

  return (
    <PranaContext.Provider value={{ getContext }}>
      {children}
    </PranaContext.Provider>
  );
};

export const usePranaContext = () => {
  return useContext(PranaContext);
};