const FALLBACK_KEY = 'pk_test_cGxlYXNlZC16ZWJyYS01OC5jbGVyay5hY2NvdW50cy5kZXYk'
export const CLERK_PUBLISHABLE_KEY = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY || FALLBACK_KEY
export const CLERK_ENABLED = Boolean(CLERK_PUBLISHABLE_KEY)


